_wandb:
    value:
        cli_version: 0.22.2
        e:
            4j0e63oalu1tuqiwlxl1gzx59zo7iapi:
                codePath: src/evaluate_model.py
                codePathLocal: evaluate_model.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "520120602624"
                        used: "121460002816"
                email: sllmdj05@gmail.com
                executable: /home/sllmdj05/.pyenv/versions/third/bin/python
                git:
                    commit: 675634927b0facded23e3804ece07a78c8ab3d95
                    remote: https://github.com/sllm05/3rd_project.git
                gpu: Tesla V100-SXM2-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-SXM2-16GB
                      uuid: GPU-f17be017-91a2-6af4-8438-0493e29b77fb
                host: instance-20251021-025950
                memory:
                    total: "31538257920"
                os: Linux-6.8.0-1041-gcp-x86_64-with-glibc2.35
                program: /home/sllmdj05/3rd_project/src/evaluate_model.py
                python: CPython 3.11.8
                root: /home/sllmdj05/3rd_project/src
                startedAt: "2025-10-21T07:12:54.231351Z"
                writerId: 4j0e63oalu1tuqiwlxl1gzx59zo7iapi
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.8
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
model:
    value: naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B
